<a href="https://colab.research.google.com/github/wranidlo/Autoencoder/blob/master/Autoencoder_typu_LSTM_Patryk_Bary%C5%82a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Patryk Baryła 
136216

# 1 Budowa Autoencodera LSTM odtwarzającego sekwencje liczb

## 1.1 Budowa modelu

In [0]:
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.layers import Input, LSTM,Dense, RepeatVector, TimeDistributed
from tensorflow.keras.optimizers import Adam
from keras.utils import plot_model
import matplotlib.pyplot as plt
import numpy as np

sequence = np.array([0.111,1.222,0.99,0.444,0.555])
seq_len= len(sequence)
sequence = sequence.reshape((1, seq_len, 1))

number_model = Sequential()
number_model.add(LSTM(100, activation='relu', input_shape=(seq_len,1)))
number_model.add(RepeatVector(seq_len))
number_model.add(LSTM(100, activation='relu', return_sequences=True))
number_model.add(TimeDistributed(Dense(1)))


Using TensorFlow backend.


##1.2 Kompilacja modelu

In [0]:
number_model.compile(optimizer='adam', loss='mse')

## 1.3 Zasilenie modelu danymi - trenowanie i testowanie

In [0]:
number_model.fit(sequence, sequence, epochs=300, verbose=0)
prediction = number_model.predict(sequence, verbose=0)
print(prediction[0,:,0])

[0.11096953 1.2220011  0.9899885  0.44400543 0.55497974]


# 2 Autoencoder LSTM dla wiadomości zapisanych w języku naturalnym

In [0]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
import numpy as np

messege = "this is not real messege it is test messege"
input_data = messege.split()
print("Zadane wyrażenie : ",input_data)
values = array(input_data)
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print("Wyrażenie jako one-hot : ")
print(onehot_encoded)
seq_len= len(input_data)
one_hot_len = len(onehot_encoded[0])
data = np.array(onehot_encoded).reshape((1, seq_len,one_hot_len))

model_word = Sequential()
model_word.add(LSTM(100, activation='relu', input_shape=(seq_len,one_hot_len)))
model_word.add(RepeatVector(seq_len))
model_word.add(LSTM(100, activation='relu', return_sequences=True))
model_word.add(TimeDistributed(Dense(one_hot_len)))

model_word.compile(optimizer='adam', loss='mse')

model_word.fit(data, data, epochs=300, verbose=0)

pred = model_word.predict(data, verbose=0)
print("Wyniki")
for e in pred[0]:
  print(np.argmax(e), " - ", label_encoder.inverse_transform([argmax(e)]))




Zadane wyrażenie :  ['this', 'is', 'not', 'real', 'messege', 'it', 'is', 'test', 'messege']
Wyrażenie jako one-hot : 
[[0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0.]]
Wyniki
6  -  ['this']
0  -  ['is']
3  -  ['not']
4  -  ['real']
2  -  ['messege']
1  -  ['it']
0  -  ['is']
5  -  ['test']
2  -  ['messege']
